[18.0][MIG] storage_backend: Migration to 18.0
thienvh332/storage pull request #4
Opened 2024-10-14 09:16 UTC by thienvh332

OCA Port:
- #3

2024-10-14 10:38 UTC, nguyenminhchien requested changes
@thienvh332 there are much more commits (mentioned in the card) to check and port. please spend time on them one by one. Create a separated commit for blacklist if needed.

2024-10-15 08:19 UTC, thienvh332 commented
> @thienvh332 there are much more commits (mentioned in the card) to check and port. please spend time on them one by one. Create a separated commit for blacklist if needed.

Hi @nguyenminhchien ,
I checked all the missing commits. All of them are false positives. They are not really missing.
Thanks.

2024-10-15 09:11 UTC, nguyenminhchien requested changes
![image](https://github.com/user-attachments/assets/677c13b1-abea-437f-977a-d0596eb22179)

I don't see these 2 missing commits. Port them or add to blacklist

2024-10-15 09:44 UTC, nguyenminhchien approved these changes

2024-12-04 05:25 UTC, closed without merging